version: "3"
services:
  nginx:
    container_name: nginx
    image: nginx
    restart: always
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./cert/cert.pem:/etc/nginx/cert/cert.pem
      - ./cert/key.pem:/etc/nginx/cert/key.pem
    networks:
      - jisu-network
    environment:
      - TZ=Asia/Seoul
    depends_on:
      - jisu_api

  jisu_api:
    build:
      dockerfile: Dockerfile
      context: .
      target: development
    volumes:
      - .:/usr/src/app
    env_file:
      - .env
    command: npm run start:dev
    ports:
      - '8000:8000'
    depends_on:
      - postgres
      - redis
    networks:
      - jisu-network

  postgres:
    container_name: postgres
    image: postgres:latest
    ports:
      - "5432:5432"
    env_file:
      - docker.env
    networks:
      - jisu-network

  mysql:
    image: mysql:8.0
    container_name: mysql
    ports:
      - 3306:3306 # HOST:CONTAINER
    environment:
      MYSQL_ROOT_PASSWORD: jisupassword
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci

  redis:
    container_name: redis
    image: "redis:alpine"
    env_file:
      - .env
    ports:
      - "6379:6379"
    networks:
      - jisu-network

networks:
  jisu-network:
    driver: bridge

